// <auto-generated />
using GraphRag.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphRag.EFCore.Migrations.SqlServerMigrations
{
    [DbContext(typeof(GraphRagDbContext))]
    partial class GraphRagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphRag.EFCore.Entities.GraphEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_GraphEntity_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_GraphEntity_Type");

                    b.ToTable("GraphEntity", (string)null);
                });

            modelBuilder.Entity("GraphRag.EFCore.Entities.GraphEntityAlias", b =>
                {
                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntityId", "Alias");

                    b.HasIndex("Alias")
                        .HasDatabaseName("IX_GraphEntityAlias_Alias");

                    b.ToTable("GraphEntityAlias", (string)null);
                });

            modelBuilder.Entity("GraphRag.EFCore.Entities.GraphEntityAlias", b =>
                {
                    b.HasOne("GraphRag.EFCore.Entities.GraphEntity", "Entity")
                        .WithMany("Aliases")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("GraphRag.EFCore.Entities.GraphEntity", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
