// <auto-generated />
using System;
using GraphRag.ITSM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphRag.ITSM.Migrations.SqlServerMigrations
{
    [DbContext(typeof(ItsmDbContext))]
    partial class ItsmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphRag.ITSM.Entities.AgentGroupMembership", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RoleInGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgentId", "AssignmentGroupId", "AssignedAt");

                    b.HasIndex("AssignmentGroupId");

                    b.ToTable("AgentGroupMemberships");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.AssignmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SupportTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_AssignmentGroups_ExternalId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssignmentGroups");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingDaysMask")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("WorkingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WorkingHoursStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_BusinessCalendars_ExternalId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessCalendars");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessServiceConsumer", b =>
                {
                    b.Property<Guid>("BusinessServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusinessServiceId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BusinessServiceConsumers");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.CalendarHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessCalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCalendarId", "Date")
                        .IsUnique();

                    b.ToTable("CalendarHolidays");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Category_ExternalId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CIType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_ConfigurationItem_ExternalId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("ConfigurationItem", (string)null);

                    b.HasDiscriminator<string>("CIType").HasValue("ConfigurationItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItemDependency", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DependencyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("ConfigurationItemDependencies");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItemSupport", b =>
                {
                    b.Property<Guid>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnicalServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConfigurationItemId", "TechnicalServiceId");

                    b.HasIndex("TechnicalServiceId");

                    b.ToTable("ConfigurationItemSupports");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Impact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Impact_ExternalId");

                    b.ToTable("Impact", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.OperationalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_OperationalEvent_ExternalId");

                    b.HasIndex("PerformedById");

                    b.HasIndex("TicketId", "EventTimestamp");

                    b.ToTable("OperationalEvent", (string)null);

                    b.HasDiscriminator<string>("EventType").HasValue("OperationalEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Organizations_ExternalId");

                    b.HasIndex("ParentOrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Person_ExternalId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator<string>("PersonType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Priority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DerivedFromImpactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DerivedFromUrgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DerivedFromImpactId");

                    b.HasIndex("DerivedFromUrgencyId");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Priority_ExternalId");

                    b.ToTable("Priority", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Service_ExternalId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Service", (string)null);

                    b.HasDiscriminator<string>("ServiceType").HasValue("Service");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceLevelAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppliesToPriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppliesToServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessCalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double?>("TargetAvailabilityPercent")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("TargetDuration")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToPriorityId");

                    b.HasIndex("AppliesToServiceId");

                    b.HasIndex("BusinessCalendarId");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_ServiceLevelAgreements_ExternalId");

                    b.HasIndex("Name");

                    b.ToTable("ServiceLevelAgreements");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceSupportGroup", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("ServiceId", "AssignmentGroupId");

                    b.HasIndex("AssignmentGroupId");

                    b.ToTable("ServiceSupportGroups");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Severity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Severity_ExternalId");

                    b.ToTable("Severity", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.SlaMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BreachStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ElapsedDuration")
                        .HasColumnType("time");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<TimeSpan>("PauseDuration")
                        .HasColumnType("time");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ServiceLevelAgreementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StopTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("TargetDuration")
                        .HasColumnType("time");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_SlaMeasurements_ExternalId");

                    b.HasIndex("ServiceLevelAgreementId");

                    b.HasIndex("TicketId", "ServiceLevelAgreementId");

                    b.ToTable("SlaMeasurements");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Status_ExternalId");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TechnicalServiceEnablement", b =>
                {
                    b.Property<Guid>("TechnicalServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TechnicalServiceId", "BusinessServiceId");

                    b.HasIndex("BusinessServiceId");

                    b.ToTable("TechnicalServiceEnablements");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AffectedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CurrentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("FirstResponseAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ImpactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PendingAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolutionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ResolverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SeverityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("SlaResolutionDeadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SlaResponseDeadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UrgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasEscalated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AffectedUserId");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("AssignedGroupId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Ticket_ExternalId");

                    b.HasIndex("ImpactId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("OpenedAt");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ResolutionGroupId");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("ResolverId");

                    b.HasIndex("SeverityId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UrgencyId");

                    b.HasIndex("CurrentStatusId", "PriorityId");

                    b.ToTable("Ticket", (string)null);

                    b.HasDiscriminator<string>("TicketType").HasValue("Ticket");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketAffectedCI", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("TicketId", "ConfigurationItemId");

                    b.HasIndex("ConfigurationItemId");

                    b.ToTable("TicketAffectedCIs");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketAffectedService", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("TicketId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("TicketAffectedServices");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RelationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("SourceTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetTicketId");

                    b.HasIndex("SourceTicketId", "TargetTicketId", "RelationKind")
                        .IsUnique();

                    b.ToTable("TicketRelations");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Urgency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Urgency_ExternalId");

                    b.ToTable("Urgency", (string)null);
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Vendors_ExternalId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Application", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.ConfigurationItem");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Application");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.CloudResource", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.ConfigurationItem");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CloudResource");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.DatabaseCI", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.ConfigurationItem");

                    b.Property<string>("Engine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Database");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.NetworkDevice", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.ConfigurationItem");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("NetworkDevice");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Server", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.ConfigurationItem");

                    b.Property<string>("Hostname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ConfigurationItem", t =>
                        {
                            t.Property("IpAddress")
                                .HasColumnName("Server_IpAddress");
                        });

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.AssignmentEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<Guid?>("FromAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ToAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ToGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FromAgentId");

                    b.HasIndex("FromGroupId");

                    b.HasIndex("ToAgentId");

                    b.HasIndex("ToGroupId");

                    b.HasDiscriminator().HasValue("Assignment");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ClosureEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<string>("ClosureCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Closure");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.EscalationEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<string>("NewTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Escalation");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ReassignmentEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("OperationalEvent", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("ReassignmentEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Reassignment");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ReopenEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("OperationalEvent", t =>
                        {
                            t.Property("Reason")
                                .HasColumnName("ReopenEvent_Reason");
                        });

                    b.HasDiscriminator().HasValue("Reopen");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ResolutionEvent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<string>("ResolutionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Resolution");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.StatusTransition", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.OperationalEvent");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("TimeInFromStatus")
                        .HasColumnType("time");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasDiscriminator().HasValue("StatusTransition");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Agent", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Person");

                    b.Property<string>("SupportTier")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessService", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Service");

                    b.Property<string>("BusinessCriticality")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Business");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceCatalogItem", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Service");

                    b.Property<string>("CatalogCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StandardFulfillmentTime")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("Catalog");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceOffering", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Service");

                    b.Property<Guid?>("BusinessServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportTier")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BusinessServiceId");

                    b.HasDiscriminator().HasValue("Offering");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TechnicalService", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Service");

                    b.Property<string>("EnvironmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Technical");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ChangeRequest", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Ticket");

                    b.Property<DateTimeOffset?>("ActualEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("PlannedEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PlannedStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasDiscriminator().HasValue("ChangeRequest");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Incident", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Ticket");

                    b.Property<Guid?>("CausedByProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolvedByChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CausedByProblemId");

                    b.HasIndex("ResolvedByChangeId");

                    b.HasDiscriminator().HasValue("Incident");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Problem", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Ticket");

                    b.Property<string>("KnownErrorArticleRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workaround")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Problem");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceRequest", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Ticket");

                    b.Property<Guid?>("RequestedCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RequestedCatalogItemId");

                    b.HasDiscriminator().HasValue("ServiceRequest");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketTask", b =>
                {
                    b.HasBaseType("GraphRag.ITSM.Entities.Ticket");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ParentTicketId");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.AgentGroupMembership", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Agent", "Agent")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "AssignmentGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("AssignmentGroup");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessServiceConsumer", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.BusinessService", "BusinessService")
                        .WithMany("ConsumedBy")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessService");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.CalendarHoliday", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.BusinessCalendar", "BusinessCalendar")
                        .WithMany("Holidays")
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCalendar");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Category", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItem", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItemDependency", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.ConfigurationItem", "Source")
                        .WithMany("DependsOn")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.ConfigurationItem", "Target")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItemSupport", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.ConfigurationItem", "ConfigurationItem")
                        .WithMany("SupportedTechnicalServices")
                        .HasForeignKey("ConfigurationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.TechnicalService", "TechnicalService")
                        .WithMany("SupportedByCIs")
                        .HasForeignKey("TechnicalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationItem");

                    b.Navigation("TechnicalService");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.OperationalEvent", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Agent", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "Ticket")
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Organization", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Organization", "ParentOrganization")
                        .WithMany("Children")
                        .HasForeignKey("ParentOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentOrganization");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Person", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Priority", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Impact", "DerivedFromImpact")
                        .WithMany()
                        .HasForeignKey("DerivedFromImpactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Urgency", "DerivedFromUrgency")
                        .WithMany()
                        .HasForeignKey("DerivedFromUrgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DerivedFromImpact");

                    b.Navigation("DerivedFromUrgency");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Service", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceLevelAgreement", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Priority", "AppliesToPriority")
                        .WithMany()
                        .HasForeignKey("AppliesToPriorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Service", "AppliesToService")
                        .WithMany()
                        .HasForeignKey("AppliesToServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.BusinessCalendar", "BusinessCalendar")
                        .WithMany()
                        .HasForeignKey("BusinessCalendarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppliesToPriority");

                    b.Navigation("AppliesToService");

                    b.Navigation("BusinessCalendar");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceSupportGroup", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "AssignmentGroup")
                        .WithMany("SupportedServices")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Service", "Service")
                        .WithMany("SupportGroups")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentGroup");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.SlaMeasurement", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.ServiceLevelAgreement", "ServiceLevelAgreement")
                        .WithMany()
                        .HasForeignKey("ServiceLevelAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "Ticket")
                        .WithMany("SlaMeasurements")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLevelAgreement");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TechnicalServiceEnablement", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.BusinessService", "BusinessService")
                        .WithMany("EnabledBy")
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.TechnicalService", "TechnicalService")
                        .WithMany("Enables")
                        .HasForeignKey("TechnicalServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BusinessService");

                    b.Navigation("TechnicalService");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Ticket", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Person", "AffectedUser")
                        .WithMany()
                        .HasForeignKey("AffectedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Agent", "AssignedAgent")
                        .WithMany()
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "AssignedGroup")
                        .WithMany()
                        .HasForeignKey("AssignedGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Status", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Impact", "Impact")
                        .WithMany()
                        .HasForeignKey("ImpactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Person", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "ResolutionGroup")
                        .WithMany()
                        .HasForeignKey("ResolutionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Agent", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Category", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Urgency", "Urgency")
                        .WithMany()
                        .HasForeignKey("UrgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AffectedUser");

                    b.Navigation("AssignedAgent");

                    b.Navigation("AssignedGroup");

                    b.Navigation("Category");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Impact");

                    b.Navigation("Priority");

                    b.Navigation("Requester");

                    b.Navigation("ResolutionGroup");

                    b.Navigation("Resolver");

                    b.Navigation("Severity");

                    b.Navigation("Subcategory");

                    b.Navigation("Urgency");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketAffectedCI", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.ConfigurationItem", "ConfigurationItem")
                        .WithMany("Tickets")
                        .HasForeignKey("ConfigurationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "Ticket")
                        .WithMany("AffectedConfigurationItems")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationItem");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketAffectedService", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Service", "Service")
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "Ticket")
                        .WithMany("AffectedServices")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketRelation", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "SourceTicket")
                        .WithMany("RelatedFrom")
                        .HasForeignKey("SourceTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "TargetTicket")
                        .WithMany("RelatedTo")
                        .HasForeignKey("TargetTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceTicket");

                    b.Navigation("TargetTicket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.AssignmentEvent", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Agent", "FromAgent")
                        .WithMany()
                        .HasForeignKey("FromAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "FromGroup")
                        .WithMany()
                        .HasForeignKey("FromGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.Agent", "ToAgent")
                        .WithMany()
                        .HasForeignKey("ToAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.AssignmentGroup", "ToGroup")
                        .WithMany()
                        .HasForeignKey("ToGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FromAgent");

                    b.Navigation("FromGroup");

                    b.Navigation("ToAgent");

                    b.Navigation("ToGroup");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.StatusTransition", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Status", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraphRag.ITSM.Entities.Status", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceOffering", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.BusinessService", "BusinessService")
                        .WithMany()
                        .HasForeignKey("BusinessServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessService");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Incident", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Problem", "CausedByProblem")
                        .WithMany()
                        .HasForeignKey("CausedByProblemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraphRag.ITSM.Entities.ChangeRequest", "ResolvedByChange")
                        .WithMany()
                        .HasForeignKey("ResolvedByChangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CausedByProblem");

                    b.Navigation("ResolvedByChange");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ServiceRequest", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.ServiceCatalogItem", "RequestedCatalogItem")
                        .WithMany()
                        .HasForeignKey("RequestedCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequestedCatalogItem");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TicketTask", b =>
                {
                    b.HasOne("GraphRag.ITSM.Entities.Ticket", "ParentTicket")
                        .WithMany()
                        .HasForeignKey("ParentTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTicket");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.AssignmentGroup", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("SupportedServices");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessCalendar", b =>
                {
                    b.Navigation("Holidays");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.ConfigurationItem", b =>
                {
                    b.Navigation("DependedOnBy");

                    b.Navigation("DependsOn");

                    b.Navigation("SupportedTechnicalServices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Organization", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Service", b =>
                {
                    b.Navigation("SupportGroups");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Ticket", b =>
                {
                    b.Navigation("AffectedConfigurationItems");

                    b.Navigation("AffectedServices");

                    b.Navigation("Events");

                    b.Navigation("RelatedFrom");

                    b.Navigation("RelatedTo");

                    b.Navigation("SlaMeasurements");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.Agent", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.BusinessService", b =>
                {
                    b.Navigation("ConsumedBy");

                    b.Navigation("EnabledBy");
                });

            modelBuilder.Entity("GraphRag.ITSM.Entities.TechnicalService", b =>
                {
                    b.Navigation("Enables");

                    b.Navigation("SupportedByCIs");
                });
#pragma warning restore 612, 618
        }
    }
}
