namespace GraphRag.NLP.Models
{
    // Don't start by asking “what information can I extract?” Start with a constrained ontology
    // of ITAM terms and relations. Then ask “what information can I extract that fits into this ontology?”

    public class ItamCorpus
    {
        public static readonly string[] ItamTerms = new string[]
        {
            // Core asset types
            "asset",
            "IT asset",
            "hardware asset",
            "software asset",
            "digital asset",
            "cloud asset",
            "virtual asset",
            "physical asset",
            "fixed asset",
            "consumable",
            "component",
            "peripheral",
            "accessory",
            "spare part",

            // Hardware
            "device",
            "endpoint",
            "workstation",
            "desktop",
            "laptop",
            "server",
            "mainframe",
            "mobile device",
            "smartphone",
            "tablet",
            "printer",
            "scanner",
            "monitor",
            "network device",
            "router",
            "switch",
            "firewall",
            "storage device",
            "SAN",
            "NAS",
            "IoT device",

            // Software
            "software",
            "application",
            "operating system",
            "middleware",
            "database",
            "SaaS",
            "on-premises software",
            "package",
            "installation",
            "instance",
            "version",
            "edition",
            "build",
            "patch",
            "update",
            "upgrade",

            // Licensing
            "license",
            "license key",
            "entitlement",
            "subscription",
            "license type",
            "perpetual license",
            "term license",
            "concurrent license",
            "named user license",
            "device license",
            "per-core license",
            "per-processor license",
            "site license",
            "OEM license",
            "volume license",
            "true-up",
            "true-down",
            "license reconciliation",
            "effective license position",
            "ELP",
            "software compliance",
            "software audit",
            "unauthorized software",
            "software metering",
            "usage tracking",

            // Lifecycle
            "asset lifecycle",
            "procurement",
            "request",
            "purchase order",
            "PO",
            "invoice",
            "receipt",
            "deployment",
            "provisioning",
            "assignment",
            "in use",
            "in stock",
            "in storage",
            "reserved",
            "retired",
            "decommissioned",
            "disposed",
            "disposal",
            "end of life",
            "EOL",
            "end of support",
            "EOS",
            "refresh cycle",
            "return",
            "reclamation",
            "harvesting",

            // Financial
            "cost",
            "acquisition cost",
            "total cost of ownership",
            "TCO",
            "depreciation",
            "amortization",
            "book value",
            "residual value",
            "capital expenditure",
            "CapEx",
            "operational expenditure",
            "OpEx",
            "chargeback",
            "showback",
            "budget",
            "warranty",
            "maintenance contract",
            "support contract",

            // Vendors & contracts
            "vendor",
            "supplier",
            "manufacturer",
            "publisher",
            "reseller",
            "contract",
            "agreement",
            "master agreement",
            "SLA",
            "renewal",
            "expiration",

            // Identification
            "asset tag",
            "barcode",
            "serial number",
            "asset ID",
            "MAC address",
            "IP address",
            "hostname",
            "product key",
            "SKU",
            "model",
            "manufacturer part number",

            // Repository & discovery
            "asset register",
            "asset repository",
            "CMDB",
            "configuration item",
            "CI",
            "inventory",
            "stock",
            "warehouse",
            "location",
            "discovery",
            "auto-discovery",
            "reconciliation",
            "normalization",

            // Governance & standards
            "ITAM",
            "SAM",
            "HAM",
            "software asset management",
            "hardware asset management",
            "ISO 19770",
            "ITIL",
            "policy",
            "compliance",
            "audit",
            "governance"
        };

        public static readonly string[] ItamRelations = new string[]
        {
            // Ownership & assignment
            "owned by",
            "assigned to",
            "used by",
            "allocated to",
            "reserved for",
            "managed by",
            "administered by",
            "custodian of",

            // Location
            "located at",
            "stored in",
            "shipped to",
            "transferred to",
            "moved from",

            // Composition & topology
            "part of",
            "component of",
            "contains",
            "installed on",
            "hosted on",
            "runs on",
            "connected to",
            "attached to",
            "paired with",
            "bundled with",

            // Software–hardware
            "deployed on",
            "provisioned to",
            "requires",
            "compatible with",
            "incompatible with",
            "depends on",
            "dependency of",
            "supersedes",
            "superseded by",
            "upgrades",
            "downgrades",

            // Licensing
            "licensed to",
            "licensed under",
            "covered by",
            "entitled to",
            "consumes license",
            "allocated from",
            "reallocated to",
            "harvested from",
            "compliant with",
            "non-compliant with",
            "over-licensed",
            "under-licensed",

            // Procurement & vendor
            "purchased from",
            "supplied by",
            "manufactured by",
            "published by",
            "resold by",
            "acquired via",
            "invoiced by",
            "ordered on",

            // Contracts & warranty
            "governed by",
            "under contract",
            "under warranty",
            "under maintenance",
            "supported by",
            "renewed on",
            "expires on",

            // Lifecycle transitions
            "procured on",
            "received on",
            "deployed on",
            "activated on",
            "retired on",
            "decommissioned on",
            "disposed on",
            "replaced by",
            "replaces",

            // Financial
            "depreciated over",
            "charged to",
            "budgeted under",
            "capitalized as",

            // Discovery & inventory
            "discovered by",
            "reconciled with",
            "recorded in",
            "tracked in",
            "tagged with",
            "identified by",

            // Categorization
            "categorized as",
            "classified as",
            "modeled as",
            "belongs to"
        };
    }
}
