<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphRag.Core\GraphRag.Core.csproj" />
    <ProjectReference Include="..\GraphRag.Graph\GraphRag.Graph.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="YamlDotNet" Version="18.1.0" />
	</ItemGroup>
	
</Project>
